import {
  paystack,
  femi,
  kuda,
  multichoice,
  netflix,
  prime,
} from "@/public/Image";
const Mymanager = [
  {
    manager: "Funke Obafemi",
    assigned_to: netflix,
    paystack,
    kuda,
    multichoice,
    netflix,
    prime,
    manager_img: femi,
    manager_id: "01009653",
    email_address: "funke@gmail.com",
    date: "12/04/23, 09:11:04",
  },
  {
    manager: "Seyi Adeyemi",
    assigned_to: paystack,
    kuda,
    multichoice,
    netflix,
    prime,
    manager_img: femi,
    manager_id: "01009653",
    email_address: "seyi@gmail.com",
    date: "12/04/23, 09:11:04",
  },
  {
    manager: "kunle Obafemi",
    assigned_to: paystack,
    kuda,
    multichoice,
    netflix,
    prime,
    manager_img: femi,
    manager_id: "01009653",
    email_address: "kunle@gmail.com",
    date: "12/04/23, 09:11:04",
  },
  {
    manager: "Taiwo Aremu",
    assigned_to: paystack,
    kuda,
    multichoice,
    netflix,
    prime,
    manager_img: femi,
    manager_id: "01009653",
    email_address: "taiwo@gmail.com",
    date: "12/04/23, 09:11:04",
  },
  {
    manager: "Bolu Adisa",
    assigned_to: paystack,
    kuda,
    multichoice,
    netflix,
    prime,
    manager_img: femi,
    manager_id: "01009653",
    email_address: "funke@gmail.com",
    type: "bolu@gmail.com",
    date: "12/04/23, 09:11:04",
  },
  {
    manager: "Abdulsalam Sodiq",
    assigned_to: paystack,
    femi,
    kuda,
    multichoice,
    netflix,
    prime,
    manager_img: femi,
    manager_id: "01009653",
    email_address: "salam@gmail.com",
    type: "Yvonne@gmail.com",
    date: "12/04/23, 09:11:04",
  },
];

export { Mymanager };
