import { femi, atm, visa, master_card } from "@/public/Image";
import Image from "next/image";
const tokenizecards = [
  {
    service_name: "USSD 1",
    client: "Client A",
    service_type: "Push",
    Associated_shortcode: "2334,2535",
    route: "Route A",
  },
  {
    service_name: "USSD 1",
    client: "Client A",
    service_type: "Push",
    Associated_shortcode: "2334,2535",
    route: "Route A",
  },
  {
    service_name: "USSD 1",
    client: "Client A",
    service_type: "Push",
    Associated_shortcode: "2334,2535",
    route: "Route A",
  },
  {
    service_name: "USSD 1",
    client: "Client A",
    service_type: "Push",
    Associated_shortcode: "2334,2535",
    route: "Route A",
  },
  {
    service_name: "USSD 1",
    client: "Client A",
    service_type: "Push",
    Associated_shortcode: "2334,2535",
    route: "Route A",
  },
  {
    service_name: "USSD 1",
    client: "Client A",
    service_type: "Push",
    Associated_shortcode: "2334,2535",
    route: "Route A",
  },
  {
    service_name: "USSD 1",
    client: "Client A",
    service_type: "Push",
    Associated_shortcode: "2334,2535",
    route: "Route A",
  },
];
const transactionLogs = [
  {
    date: "12/04/23, 09:11:04",
    number_of_contact: "4",
    route: "MTN Route",
    ussd_type: "PUSH",
    shortcode: "31000",
    ussd_session: "31000",
    amount: "5,000",
    action: "View",
  },
  {
    date: "12/04/23, 09:11:04",
    number_of_contact: "4",
    route: "MTN Route",
    ussd_type: "PUSH",
    shortcode: "31000",
    ussd_session: "31000",
    amount: "5,000",
    action: "View",
  },
  {
    date: "12/04/23, 09:11:04",
    number_of_contact: "4",
    route: "MTN Route",
    ussd_type: "PUSH",
    shortcode: "31000",
    ussd_session: "31000",
    amount: "5,000",
    action: "View",
  },
  {
    date: "12/04/23, 09:11:04",
    number_of_contact: "4",
    route: "MTN Route",
    ussd_type: "PUSH",
    shortcode: "31000",
    ussd_session: "31000",
    amount: "5,000",
    action: "View",
  },
  {
    date: "12/04/23, 09:11:04",
    number_of_contact: "4",
    route: "MTN Route",
    ussd_type: "PUSH",
    shortcode: "31000",
    ussd_session: "31000",
    amount: "5,000",
    action: "View",
  },
  {
    date: "12/04/23, 09:11:04",
    number_of_contact: "4",
    route: "MTN Route",
    ussd_type: "PUSH",
    shortcode: "31000",
    ussd_session: "31000",
    amount: "5,000",
    action: "View",
  },
  {
    date: "12/04/23, 09:11:04",
    number_of_contact: "4",
    route: "MTN Route",
    ussd_type: "PUSH",
    shortcode: "31000",
    ussd_session: "31000",
    amount: "5,000",
    action: "View",
  },
];

export { tokenizecards, transactionLogs };
